config/routes.rb
Rails.application.routes.draw do
  resources :posts
  devise_for :users
  root to: 'homes#top'
  get 'about', to: 'homes#about'

  # 管理者ログイン
  devise_for :admin, skip: [:registrations, :password], controllers: {
    sessions: 'admin/sessions'
  }


  # 管理者管理
  namespace :admin do
    # get 'dashboards', to: 'dashboards#index' この部分不要
    get 'users', to: 'users#index'
    resources :users, only: [:index, :show, :destroy]
    resources :reviews, only: [:index, :destroy] # レビュー管理者
    resources :posts, only: [:show, :edit, :update, :destroy] # 管理者用：投稿詳細ページ＆削除＆編集　# do これは管理者用コメント削除で必要だが一旦保留
      # resources :comments, only: [:destroy], module: :posts 管理者用コメント削除一旦コメントアウト
      # end 管理者用コメント削除一旦コメントアウト
  end

  # エンドユーザーの管理
  namespace :public do
    resources :users, only: [:show]
  end


  resources :posts do
    collection do
      get :search # 投稿検索機能
      get :tagged, to: 'posts#index', as: :tagged # タグ検索
    end

    resource :favorite, only: [:create, :destroy] # いいね機能
    resources :comments, only: [:create, :destroy] # コメント機能
  end
  
  resources :users, only: [:show, :edit, :update] do
    member do
      delete :destroy_account # ユーザー退会処理
    end
    collection do
      get :mypage # マイページ
      get :search # ユーザー検索機能
    end
  end

  post 'guest_login', to: 'users#guest_login'  # ゲストログイン
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/homes/about.html.erb
<div style="margin-left: 30%; text-align: left; margin-top: 50px;">
  <h1>「ポイ活広場」とは？</h1>
  <p>
    「ポイ活広場」は、ポイント還元率や使いやすさなど、各種ポイントサービスを評価し、比較するためのレビューサイトです。
  </p>
  <p>
    ポイントサービスの還元率や使いやすさは、それぞれ大きく異なります。情報が分散して比較しづらいという課題を解決するために、このサイトを作成しました。
  </p>
  <p>
    「ポイ活広場」で、自分にぴったりのポイントサービスを見つけて、日々の生活をさらにお得にしましょう！
  </p>
  <p>
    <% if user_signed_in? %>
      <%= link_to "マイページへ", mypage_users_path, class: "btn btn-outline-secondary ms-2" %>
    <% end %>
  </p>
</div>

app/views/homes/top.html.erb
<div style="margin-left: 30%; text-align: left; margin-top: 50px;">
  <h1>ポイ活広場へようこそ！</h1>
  <p>
    この「ポイ活広場」は、ポイントサービスの還元率や使いやすさを比較し、あなたに最適なサービスを見つけるためのレビューサイトです。
  </p>
  <p>
    ユーザー同士でレビューや評価を共有しながら、効率よくお得を実現しましょう！すべてのポイ活ユーザーをサポートします。
  </p>
  <p>
    さあ、あなたにぴったりのポイントサービスを探し始めましょう！
  </p>
</div>

<!--  管理者ログインリンク 管理者アクセスしやすいように（本来削除） -->
<% unless user_signed_in? || admin_signed_in? %>
  <div style="margin-left: 30%; text-align: right; margin-top: 20px;">
    <%= link_to "管理者ログイン", new_admin_session_path, class: "btn btn-outline-secondary" %>
  </div>
<% end %>