config/routes.rb
Rails.application.routes.draw do
  resources :posts
  devise_for :users
  root to: 'homes#top'
  get 'about', to: 'homes#about'

  # 管理者ログイン
  devise_for :admin, skip: [:registrations, :password], controllers: {
    sessions: 'admin/sessions'
  }


  # 管理者管理
  namespace :admin do
    # get 'dashboards', to: 'dashboards#index' この部分不要
    get 'users', to: 'users#index'
    resources :users, only: [:index, :show, :destroy]
    resources :reviews, only: [:index, :destroy] # レビュー管理者
    resources :posts, only: [:show, :edit, :update, :destroy] # 管理者用：投稿詳細ページ＆削除＆編集　# do これは管理者用コメント削除で必要だが一旦保留
      # resources :comments, only: [:destroy], module: :posts 管理者用コメント削除一旦コメントアウト
      # end 管理者用コメント削除一旦コメントアウト
  end

  # エンドユーザーの管理
  namespace :public do
    resources :users, only: [:show]
  end


  resources :posts do
    collection do
      get :search # 投稿検索機能
      get :tagged, to: 'posts#index', as: :tagged # タグ検索
    end

    resource :favorite, only: [:create, :destroy] # いいね機能
    resources :comments, only: [:create, :destroy] # コメント機能
  end
  
  resources :users, only: [:show, :edit, :update] do
    member do
      delete :destroy_account # ユーザー退会処理
    end
    collection do
      get :mypage # マイページ
      get :search # ユーザー検索機能
    end
  end

  post 'guest_login', to: 'users#guest_login'  # ゲストログイン
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  acts_as_taggable_on :tags

  REWARD_RATES = ["高還元率（1%以上）", "中還元率（0.5%〜1%未満）", "低還元率（0.5%未満）", "その他"]

  validates :title, presence: true, length: { maximum: 100 }
  validates :body, presence: true
  validates :reward_rate, presence: true
  validates :rate, presence: true

  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController
  layout 'admin' # 管理者用レイアウト
  before_action :authenticate_admin! # 管理者認証
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  def show 
    @post = Post.find(params[:id])
  end

  def edit
  end

  def update
    if @post.update(post_params)
      redirect_to admin_post_path(@post), notice: "投稿が編集されました。"
    else
      render :edit
    end
  end

  def destroy
    @post.destroy
    redirect_to admin_reviews_path, notice: "投稿を削除しました。"
  end

  private

  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :body, :reward_rate, :rate, :tag_list)
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user! # すべてのユーザーがログイン必須
  before_action :set_post, only: %i[show edit update destroy]
  before_action :ensure_guest_user, only: %i[new create edit update destroy]
  before_action :ensure_correct_user, only: %i[edit update]  # ログインユーザー以外のIDで投稿編集URLにアクセス制限

  def edit
  end

  def index
    @posts = Post.all

    # キーワード検索
    if params[:query].present?
      keyword = "%#{params[:query]}%"
      @posts = @posts.where("title LIKE ? OR body LIKE ?", keyword, keyword)
    end

    # ポイント還元率検索
    if params[:reward_rate].present?
      @posts = @posts.where(reward_rate: params[:reward_rate])
    end

    # タグ検索
    if params[:tag].present?
      @posts = @posts.tagged_with(params[:tag])
    end

    # ソート機能
    case params[:sort_by]
    when 'likes' # いいね
      @posts = @posts.left_joins(:favorites)
                     .group("posts.id")
                     .order(Arel.sql('COUNT(favorites.id) DESC'))
    when 'rating' #評価ソート機能
      @posts = @posts.order(rate: :desc)
    when 'comments' # コメント数ソート機能
      @posts = @posts.left_joins(:comments)
                     .group("posts.id")
                     .order(Arel.sql('COUNT(comments.id) DESC'))
    # when 'likes_comments_rating' いいね+コメント数+評価ソート機能（順番もその通り） 後日使用する可能性があるためコメントアウト
      # @posts = @posts.left_joins(:favorites, :comments) 後日使用する可能性があるためコメントアウト
                     # .group("posts.id") 後日使用する可能性があるためコメントアウト
                     # .order(Arel.sql('COUNT(favorites.id) DESC, COUNT(comments.id) DESC, COALESCE(rate, 0) DESC')) 後日使用する可能性があるためコメントアウト
    else
      @posts = @posts.includes(:favorites, :comments).order(created_at: :desc) # 新着順表示＆いいね・コメント事前読み込み
    end
  end

  def show
    @post = Post.includes(:user, :comments).find(params[:id]) 
    @comment = Comment.new 
    @comments = @post.comments.includes(:user).order(created_at: :desc)
    @previous_post = Post.where("id < ?", @post.id).order(id: :desc).first # 「← 前の投稿」
    @next_post = Post.where("id > ?", @post.id).order(id: :asc).first # 「次の投稿 →」
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.build(post_params) # ログイン中のユーザーに紐付け

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: "投稿が完了されました" }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @post.update(post_params) # レビュー
        format.html { redirect_to @post, notice: "投稿が編集されました" }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to mypage_users_path, status: :see_other, notice: "投稿が削除されました。" }
      format.json { head :no_content }
    end
  end

  private

  # タグを許可
  def post_params
    params.require(:post).permit(:title, :body, :reward_rate, :rate, :tag_list) 
  end

  def set_post
    @post = Post.find(params[:id]) 
  rescue ActiveRecord::RecordNotFound
    redirect_to posts_path, alert: 'その投稿は存在しません。'
  end

  # ゲストユーザーの制限
  def ensure_guest_user
    if current_user.email == 'guest@example.com'
      redirect_to root_path, alert: 'ゲストユーザーはこの操作を行えません。'
    end
  end

  # ログインユーザー以外のIDで投稿編集URLにアクセス制限
  def ensure_correct_user
    unless @post.user == current_user
      redirect_to posts_path, alert: '他のユーザーの投稿は編集できません。'
    end
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= post.errors.count %> 件のエラーが発生しました:</h2>
      <ul>
        <% post.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="ms-4">
    <!-- サービス名 -->
    <div class="mb-4">
      <%= form.label :title, "サービス名" %>
      <br>
      <%= form.text_field :title, class: "form-control w-50" %>
    </div>

    <!-- サービスの特徴や使いやすさ -->
    <div class="mb-4">
      <%= form.label :body, "サービスの特徴や使いやすさ" %>
      <br>
      <%= form.text_area :body, class: "form-control w-50" %>
    </div>

    <!-- ポイント還元率 -->
    <div class="mb-4">
      <%= form.label :reward_rate, "ポイント還元率" %>
      <br>
      <%= form.select :reward_rate, ["高還元率（1%以上）", "中還元率（0.5%〜1%未満）", "低還元率（0.5%未満）", "その他"], { prompt: "選択してください" }, class: "form-select w-50" %>
    </div>

    <!-- 投稿検索機能(タグ検索) -->
    <div class="mb-4">
      <%= form.label :tag_list, "関連キーワード（タグ）" %>
      <br>
      <%= form.text_field :tag_list, class: "form-control w-50" %>
    </div>

    <!-- レビュー -->
    <div class="mb-4">
      <%= form.label :rate, "5段階評価" %>
      <div id="post_raty"></div>
      <%= form.hidden_field :rate, id: "rate_value" %>
    </div>

    <!-- ボタン -->
    <div class="mb-4">
      <% if post.persisted? %>
        <%= form.submit "更新する", class: "btn btn-primary" %>
        <%= link_to '詳細に戻る', post_path(post), class: "btn btn-secondary ms-2" %>
        <%= link_to '削除する', post_path(post), method: :delete, data: { confirm: '本当に削除しますか？' }, class: "btn btn-danger ms-2" %>
      <% else %>
        <%= form.submit "投稿する", class: "btn btn-primary" %>
        <%= link_to '一覧に戻る', posts_path, class: "btn btn-secondary ms-2" %>
      <% end %>
    </div>

  </div>
<% end %>

<!-- レビュー -->
<div id="post_raty"></div>
<script>
  if(document.getElementById("post_raty") != null){
     document.querySelector("#post_raty").textContent = '';
     let elem = document.querySelector("#post_raty");
     let opt = {
       starOff: "<%= asset_path('star-off.png') %>",    
       starOn: "<%= asset_path('star-on.png') %>",      
       scoreName: "post[rate]",
       score: <%= @post.rate || 0 %>, 
       click: function(score) { 
         document.querySelector("#rate_value").value = score; 
       }
     };
     raty(elem, opt);
  }
</script>

app/views/posts/edit.html.erb
<h1 class="mb-4 ms-4">サービス内容を編集</h1>
<%= render 'form', post: @post %>

app/views/posts/index.html.erb
<h1 class="mb-4">ポイ活サイト一覧</h1>

<%= form_with url: posts_path, method: :get, local: true do %>
  <!-- 投稿検索 -->
  <%= text_field_tag :query, params[:query], placeholder:"キーワードを入力" %>

  <!-- ポイント還元率の検索用 -->
  <%= select_tag :reward_rate, options_for_select([
      ['すべて', ''],
      ['高還元率（1%以上）', '高還元率（1%以上）'],
      ['中還元率（0.5%〜1%未満）', '中還元率（0.5%〜1%未満）'],
      ['低還元率（0.5%未満）', '低還元率（0.5%未満）'],
      ['その他', 'その他']
    ], params[:reward_rate])
  %>

  <!-- タグ検索 -->
  <%= text_field_tag :tag, params[:tag], placeholder:"関連キーワード(タグ)を入力" %>

  <!-- ソート機能 -->
  <%= select_tag :sort_by, options_for_select([
      ['指定なし', ''],
      ['いいね数（多い順）', 'likes'],
      ['コメント数（多い順）', 'comments'], 
      ['評価（高い順）', 'rating'],
      # ['いいね数＋コメント数＋評価（多い順）', 'likes_comments_rating'] 後日使用可能性があるため削除ではなくコメントアウト
    ], params[:sort_by]), class: "sort-select" %>

  <%= submit_tag "検索・並び替え", class: "btn btn-primary" %>
<% end %>

<table class="table">
  <thead>
    <tr>
      <th>投稿者</th>
      <th>投稿日</th>
      <th>サービス名</th>      
      <th>サービスの特徴や使いやすさ</th>
      <th>ポイント還元率</th>
      <th>関連キーワード（タグ）</th>
      <th>いいね数</th> 
      <th>コメント数</th>
      <th>評価</th> 
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
        <td>
          <div class="d-flex align-items-center gap-2">
            <% if post.user.avatar.attached? %>
              <%= image_tag post.user.avatar, class: "rounded-circle", size: "40x40" %>   <!-- プロフィール画像選択後 -->
            <% else %>
              <%= image_tag "no_image_hoikatsuhiroba.png", class: "rounded-circle", size: "40x40" %>  <!-- デフォルト画像 -->
            <% end %>
              <%= post.user.name %>  <!-- ユーザー名 -->
          </div>
        </td>      
        <td><%= post.created_at.strftime("%Y年%m月%d日 %H:%M") %></td>
        <td style="width: 180px; word-break: break-word;"><%= post.title %></td>        
        <td style="width: 400px; word-break: break-word;"><%= post.body %></td>
        <td><%= post.reward_rate.presence || "未設定" %></td>

        <!-- タグ -->
        <td>
          <% post.tag_list.each do |tag| %>
            <%= link_to tag, posts_path(tag: tag) %>
          <% end %>
        </td>

        <!-- いいね -->
        <td>
          <% if post.favorited_by?(current_user) %>
            <%= link_to post_favorite_path(post), method: :delete, data: { turbo_method: :delete } do %>
              ♥<%= post.favorites.count %> いいね
            <% end %>
          <% else %>
            <%= link_to post_favorite_path(post), method: :post, data: { turbo_method: :post } do %>
              ♡<%= post.favorites.count %> いいね
            <% end %>
          <% end %>
        </td>

        <!-- コメント数 -->
        <td><%= "#{post.comments.size}コメント" %></td>

        <!-- 評価 -->
        <td>
          <div id="post_raty_<%= post.id %>"></div>
          <script>
            if (document.getElementById("post_raty_<%= post.id %>") != null) {
              document.querySelector("#post_raty_<%= post.id %>").textContent = '';
              let elem = document.querySelector("#post_raty_<%= post.id %>");
              let opt = {
                starOff: "<%= asset_path('star-off.png') %>",
                starOn: "<%= asset_path('star-on.png') %>",
                readOnly: true,
                score: <%= post.rate || 0 %> 
              };
              raty(elem, opt);
            }
          </script>
        </td>

        <!-- 詳細 -->
        <td>
          <%= link_to '詳細を見る', post, class: "btn btn-primary" %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% if user_signed_in? && current_user.email != 'guest@example.com' %>
  <div>
    <%= link_to 'おすすめなポイ活サイトを投稿(新規投稿)', new_post_path, class: "btn btn-success" %>
  </div>
<% end %>

app/views/posts/new.html.erb
<h1 class="mb-4 ms-4">おすすめポイ活サイトを投稿</h1>
<%= render 'form', post: @post %>

app/views/posts/show.html.erb
<h1 class="mb-4 ms-3">ポイ活サービス詳細</h1>

<div class="d-flex justify-content-between mb-3 mx-3">
  <% if @previous_post %>
    <%= link_to '← 前の投稿', post_path(@previous_post) %>
  <% else %>
    <span></span>
  <% end %>

  <% if @next_post %>
    <%= link_to '次の投稿 →', post_path(@next_post) %>
  <% else %>
    <span></span>
  <% end %>
</div>


<div class="card p-3 ms-3">
  <p class="d-flex align-items-center gap-3">
    <span>
      <strong>投稿者名:</strong>
      <%= link_to @post.user.name, user_path(@post.user), class: "ms-2" %>
    </span>

    <% if @post.user.avatar.attached? %>
      <%= image_tag @post.user.avatar, class: "rounded-circle", size: "40x40" %>
    <% else %>
      <%= image_tag "no_image_hoikatsuhiroba.png", class: "rounded-circle", size: "40x40" %>
    <% end %>
  </p>

  <p>
    <strong>投稿日:</strong>
    <%= @post.created_at.strftime("%Y年%m月%d日 %H:%M") %>
  </p>

  <p>
    <strong>サービス名:</strong>
    <%= @post.title %>
  </p>

  <p>
    <strong>サービスの特徴や使いやすさ:</strong>
    <%= @post.body %>
  </p>

  <p>
    <strong>ポイント還元率:</strong>
    <%= @post.reward_rate.presence || "未設定" %> 
  </p>

  <!-- 投稿検索機能(タグ検索)-->
  <p>
    <strong>関連キーワード（タグ）:</strong>
    <% if @post.tag_list.present? %>
      <% @post.tag_list.each do |tag| %>
        <%= link_to tag, posts_path(tag: tag) %>
      <% end %>
    <% else %>
      <span></span>
    <% end %>
  </p>

  <!-- レビュー（5段階評価） -->
  <p>
    <strong>評価:</strong>
    <div id="post_raty"></div>
  </p>

  <% if @post.favorited_by?(current_user) %>
    <%= link_to post_favorite_path(@post), method: :delete do %>
      ♥<%= @post.favorites.count %> いいね
    <% end %>
  <% else %>
    <%= link_to post_favorite_path(@post), method: :post do %>
      ♡<%= @post.favorites.count %> いいね
    <% end %>
  <% end %>
</div>

<div class="mt-3 ms-3">
  <%= link_to '一覧に戻る', posts_path, class: "btn btn-secondary" %>  

  <% if @post.user == current_user %>
    <%= link_to '編集する', edit_post_path(@post), class: "btn btn-primary ms-2" %>
    <%= link_to '削除する', post_path(@post), method: :delete, data: { confirm: '本当に削除しますか？' }, class: "btn btn-danger ms-2" %>
  <% end %>
</div>

<!-- レビュー -->
<div id="post_raty"></div>
<script>
if (document.getElementById("post_raty") != null) {
  document.querySelector("#post_raty").textContent = '';
  let elem = document.querySelector("#post_raty");
  let opt = {
    starOff: "<%= asset_path('star-off.png') %>",
    starOn: "<%= asset_path('star-on.png') %>",
    readOnly: true,
    score: <%= @post.rate || 0 %>
  };
  raty(elem, opt);
}
</script>

<!-- コメント一覧 -->
<div class="card p-3 ms-3">
  <h2 class="mb-4 ms-3">コメント一覧</h2>
  <p class="ms-3 mb-0  fs-5"><strong><%= @post.comments.count %>件のコメントがあります。</strong></p>  <!-- コメント数 -->
  <div class="p-3">
    <% @comments.each do |comment| %>
      <div class="border-bottom py-2">
        <p>
          <strong><%= comment.user.name %></strong>：
          <%= comment.content %>
          <br>
          <small class="text-muted"><%= comment.created_at.strftime("%Y年%m月%d日 %H:%M") %></small>
        </p>
        <% if comment.user == current_user %>
          <%= link_to '削除', post_comment_path(@post, comment), method: :delete, data: { confirm: '本当に削除しますか？' }, class: "btn btn-danger btn-sm" %>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

<!-- コメント追加フォーム -->
<% unless current_user.email == 'guest@example.com' %>
  <div class="card p-3 ms-3">
    <h2 class="mb-4 ms-3">コメントを追加する</h2>
    <div class="p-3">
      <%= form_with model: [@post, @comment], local: true do |f| %>
        <div class="mb-3">
          <%= f.text_area :content, placeholder: 'コメントを入力してください', class: "form-control" %>
        </div>
        <div>
          <%= f.submit '送信', class: "btn btn-primary" %>
        </div>
      <% end %>
    </div>
  </div>
<% end %>