config/routes.rb
Rails.application.routes.draw do
  resources :posts
  devise_for :users
  root to: 'homes#top'
  get 'about', to: 'homes#about'

  # 管理者ログイン
  devise_for :admin, skip: [:registrations, :password], controllers: {
    sessions: 'admin/sessions'
  }


  # 管理者管理
  namespace :admin do
    # get 'dashboards', to: 'dashboards#index' この部分不要
    get 'users', to: 'users#index'
    resources :users, only: [:index, :show, :destroy]
    resources :reviews, only: [:index, :destroy] # レビュー管理者
    resources :posts, only: [:show, :edit, :update, :destroy] # 管理者用：投稿詳細ページ＆削除＆編集　# do これは管理者用コメント削除で必要だが一旦保留
      # resources :comments, only: [:destroy], module: :posts 管理者用コメント削除一旦コメントアウト
      # end 管理者用コメント削除一旦コメントアウト
  end

  # エンドユーザーの管理
  namespace :public do
    resources :users, only: [:show]
  end


  resources :posts do
    collection do
      get :search # 投稿検索機能
      get :tagged, to: 'posts#index', as: :tagged # タグ検索
    end

    resource :favorite, only: [:create, :destroy] # いいね機能
    resources :comments, only: [:create, :destroy] # コメント機能
  end
  
  resources :users, only: [:show, :edit, :update] do
    member do
      delete :destroy_account # ユーザー退会処理
    end
    collection do
      get :mypage # マイページ
      get :search # ユーザー検索機能
    end
  end

  post 'guest_login', to: 'users#guest_login'  # ゲストログイン
end

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ポイ活広場管理者画面</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet">
</head>

<body>
  <nav class="navbar navbar-expand-lg navbar-light bg-success">
    <div class="container-fluid">
      <span class="navbar-brand">ポイ活広場管理者画面</span>
      <div class="collapse navbar-collapse">
        <ul class="navbar-nav">
          <% if admin_signed_in? %>
            <li class="nav-item"><%= link_to "管理者用ユーザー一覧", admin_users_path, class: "nav-link" %></li>
            <li class="nav-item"><%= link_to "管理者用レビュー一覧", admin_reviews_path, class: "nav-link" %></li>
            <li class="nav-item"><%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: "nav-link" %></li>

          <% end %>
        </ul>
      </div>
    </div>
  </nav>

  <!-- フラッシュメッセージ -->
  <% flash.each do |key, message| %>
    <p class="<%= key %>"><%= message %></p>
  <% end %>
  
  <div class="container mt-4">
    <%= yield %>
  </div>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ポイ活広場</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet">
  </head>

  <body>
    <header>
    <nav class="navbar navbar-expand-lg" style="background-color: #f8d775;">

        <div class="container-fluid">
        <a class="navbar-brand btn btn-outline-primary py-1 px-3 fw-bold" href="<%= root_path %>">ポイ活広場</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav mx-auto">
              <li class="nav-item"><%= link_to "About", about_path, class: "nav-link" %></li>
              <% if user_signed_in? %>
                <li class="nav-item"><%= link_to "おすすめなポイ活サイトを投稿(新規投稿)", new_post_path, class: "nav-link" %></li>
                <li class="nav-item"><%= link_to "ポイ活サイト一覧", posts_path, class: "nav-link" %></li>
                <li class="nav-item"><%= link_to "マイページ", mypage_users_path, class: "nav-link" %></li>
                <li class="nav-item"><%= link_to "ユーザーを探す", search_users_path, class: "nav-link" %></li>
              <% end %>
            </ul>
            <ul class="navbar-nav">
              <% if user_signed_in? %>
                <li class="nav-item"><%= link_to "Logout", destroy_user_session_path, method: :delete, class: "btn btn-outline-danger ms-2" %></li>
              <% else %>
                <li class="nav-item"><%= link_to "Sign Up", new_user_registration_path, class: "btn btn-outline-primary ms-2" %></li>
                <li class="nav-item"><%= link_to "Sign In", new_user_session_path, class: "btn btn-primary ms-2" %></li>
                <li class="nav-item"><%= link_to "ゲストの方はこちら", guest_login_path, method: :post, class: "btn btn-primary ms-2" %></li>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>

    <% flash.each do |key, message| %>
      <p class="<%= key %>"><%= message %></p>
    <% end %>

    <%= yield %>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js"></script>
  </body>
</html>